feat: build new api
rj76/fcm-rust pull request #4
Opened 2024-01-22 13:18 UTC by adnanjpg

replace the old java-like api with a new all inclusive api

2024-01-22 13:18 UTC, adnanjpg commented
the simple_sender and the tests run fine, but the doc tests are broken, and we need to reorganize the exports to export everything necessary from lib.rs

2024-01-22 14:47 UTC, adnanjpg commented
ok so https://github.com/rj76/fcm-rust/pull/4/commits/a4dc1154a693104714637e5b9c40e084fc31b3e2 implements appropriate exports and limits visibility to internal struct

2024-01-31 17:32 UTC, adnanjpg commented
ok I believe this is ready @rj76

2024-02-04 12:26 UTC, rj76 requested changes
I love what you did in this PR, great work. There are a few small things that I noticed.

2024-02-04 12:26 UTC, rj76 commented on a.sh
> +cargo run --example simple_sender -- -t fP0EXs_HQ4Gj1sE5xBP6LP:APA91bGxDOk4GzvIvvGFPa6kDWOOHm2zYA3tUN1jYwErSBq_s27NioYjYWfUpgUW3_LIsreSw1pbtTjEpCK_cKR6AHxo1PGZ1Yd3S8lyX148I_LgKaTNYorG2QtkcwfB9Nm5yKGJ
I think this went in by mistake :)

2024-02-04 12:26 UTC, rj76 commented on src/client/mod.rs
>      }
clippy might be right about this...

2024-02-04 12:26 UTC, rj76 commented on src/client/mod.rs
> +
lets remove that println

2024-02-04 12:26 UTC, rj76 commented on src/message/tests.rs
> +    assert_eq!(msg.notification.is_none(), true);
I think we're missing a `msg.finalize()` here

2024-03-03 10:24 UTC, rj76 approved these changes

2024-03-03 10:24 UTC, merged